### ISSUE TITLE
case sensitiv Sirupsen

### ISSUE THREAD

**Issue by andreaspeters** [matrix-org/util#15]
Hi,

your are using the nice log module from Sirupsen. The problem is, you choose to use it in the "wrong" (ok, not so nice) golang way with a upper case. Sirupsen and also golangs best prectise is to use is in lower case. Now the problem is, that other modules are using logrus in lower case. That means, we are getting these bad error message:

 case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"

:-( Well, it would be great if you change to lower case. :-) And yes, it would be easier if Sirupsen stop to deliver both. :-)

Take care,
Andreas

**Comment by erikjohnston** [comment]
Fix merged!
